name: action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron:  '00 04 * * 1' # 每天早上五点自动运行，这里是标准UTC时间，换算之后是北京时间13点运行。
  workflow_dispatch:  # Allow manual triggering
    Scheduled:
      inputs:
        description: 'Scheduled Time'  # TO-DO
        required: false

jobs:
  qndxx:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: 'action'
      run: |
        python main.py
